In [1]:
!  pip install numpy 

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import numpy as np
from fractions import Fraction

# Création et Manipulation des Tableaux

In [14]:
# Création d'un tableau 1D

a = np.array([1, 2, 3, 4, 5])
print(a) 



[1 2 3 4 5]


In [15]:
# Création d'un tableau 2D

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)


[[1 2 3]
 [4 5 6]]


In [16]:
# Tableau de zéros
zeros = np.zeros((3, 4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
# Tableau de uns
ones = np.ones((2, 3))
print(ones)


[[1 1 1]
 [1 1 1]]


In [25]:
# Tableau avec des valeurs aléatoires
random = np.random.random((3, 2))
print(random)


[[0.74893976 0.11177238]
 [0.53682781 0.06464362]
 [0.08606753 0.83609516]]


In [26]:
# Tableau avec une plage de valeurs
range_array = np.arange(0, 20, 5)
print(range_array) 

[ 0  5 10 15]


In [27]:

# Modifier la forme d'un tableau sans changer ses données.
a = np.arange(6)
print(a) 

b = a.reshape((2, 3))
print(b)


[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [28]:
# Masquage et filtrage
a = np.array([1, 2, 3, 4, 5, 6])
mask = a > 3
print(mask)      
filtered = a[mask]
print(filtered)  


[False False False  True  True  True]
[4 5 6]


# Opérations Arithmétiques

In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
c = a + b
print(c)  

# Multiplication
d = a * b
print(d) 

# Exponentiation
e = a ** 2
print(e) 

[5 7 9]
[ 4 10 18]
[1 4 9]


# Matrices et vecteurs

In [30]:
# Création de vecteurs
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Création de matrices
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

# Produit matriciel

In [31]:
result = np.dot(m1, m2)
print(result)


# Utilisation de l'opérateur @
result = m1 @ m2
print(result)



[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


# Déterminant, inverse et rang

In [32]:
# Déterminant
det_m1 = np.linalg.det(m1)
print(det_m1)

# Inverse
inv_m1 = np.linalg.inv(m1)
print(inv_m1)


# Rang
rank_m1 = np.linalg.matrix_rank(m1)
print(rank_m1)  


-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
2


# Moyenne et médiane

In [34]:
a = np.array([1, 2, 3, 25, 5])

# Moyenne
mean = np.mean(a)
print(mean)

# Médiane
median = np.median(a)
print(median) 



7.2
3.0


# Variance et écart-type


In [35]:

a = np.array([1, 2, 3, 4, 5])

# Variance
variance = np.var(a)
print(variance) 

# Écart-type
std_dev = np.std(a)
print(std_dev) 

2.0
1.4142135623730951


# Corrélation et covariance

In [36]:

x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])

# Corrélation
correlation = np.corrcoef(x, y)
print(correlation)


# Covariance
covariance = np.cov(x, y)
print(covariance)

[[ 1. -1.]
 [-1.  1.]]
[[ 2.5 -2.5]
 [-2.5  2.5]]


# Tri et recherche

In [37]:
a = np.array([3, 1, 4, 1, 5, 9, 2])

# Tri
sorted_a = np.sort(a)
print(sorted_a) 


# Recherche des indices où les éléments sont supérieurs à 3
indices = np.where(a > 3)
print(indices)

[1 1 2 3 4 5 9]
[1 3 6 0 2 4 5]
(array([2, 4, 5], dtype=int64),)


# Sauvegarde de tableau en binaire et texte


In [39]:


# Création d'un tableau
a = np.array([[1, 2, 3], [4, 5, 6]])

# Sauvegarde au format .npy
np.save('array.npy', a)

# Chargement depuis .npy
loaded_a = np.load('array.npy')
print(loaded_a)

# Sauvegarde au format texte
np.savetxt('array.txt', a, delimiter=',')

# Chargement depuis texte
loaded_a_txt = np.loadtxt('array.txt', delimiter=',')
print(loaded_a_txt)

[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]


# Resolution de système d'équation
2x+3y−z=5
4x+y+2z=6
−3x+2y+4z=7​

In [9]:

# Définition de la matrice des coefficients 
A = np.array([
    [2, 3, -1],
    [4, 1, 2],
    [-3, 2, 4]
], dtype=float)

In [10]:

# Définition du vecteur des constantes 
B = np.array([5, 6, 7], dtype=float)


In [12]:

# Vérification si la matrice A est inversible
if np.linalg.det(A) != 0:
    # Résolution du système d'équations
    solution = np.linalg.solve(A, B)
    print("La solution du système est :")
    print(f"x = {Fraction(solution[0]).limit_denominator()}")
    print(f"y = {Fraction(solution[1]).limit_denominator()}")
    print(f"z = {Fraction(solution[2]).limit_denominator()}")
else:
    print("Le système n'a pas de solution unique.")


La solution du système est :
x = 5/11
y = 136/77
z = 93/77
